// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Fuzzing struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Part      string
	Condition string
	Required  string
}

type Risk struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	Abbreviation string
	Description  string
	Remediation  string
}

type Tag struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Template struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Vulnerability uuid.UUID
	Path          string
}

type Vulnerability struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             string
	Risk             uuid.UUID
	Command          string
	Severity         string
	StepsToReproduce string
	Power            string
}

type VulnerabilityFuzzing struct {
	ID              uuid.UUID
	VulnerabilityID uuid.UUID
	FuzzingID       uuid.UUID
}

type VulnerabilityTag struct {
	ID              uuid.UUID
	VulnerabilityID uuid.UUID
	TagID           uuid.UUID
}
