# docker-compose up --build
# docker-compose down --volumes
version: '3.8'
services:
  # REDIS
  redis:
    image: redis:7.2-alpine
  # POSTGRES
  db:
    image: postgres:15
    volumes:
     - bolt_data:/var/lib/postgresql/data/
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=bolt
  # # BIFROST UI
  # bifrost-ui:
  #   container_name: 'bifrost_ui'
  #   build:
  #     context: ./bifrost/bifrost-ui
  #   command: npm start
  #   volumes:
  #     - ./bifrost/bifrost-ui:/bifrost-ui/
  #   ports:
  #     - "8332:8332"
  #   environment:
  #     - DEBUG=1
  # BIFROST API
  bifrost-api:
    container_name: 'bifrost_api'
    build:
      context: ./bifrost/bifrost
    command: python manage.py runserver 0.0.0.0:8333
    volumes:
      - ./bifrost/bifrost:/bifrost/
    ports:
      - "8333:8333"
    environment:
      - DEBUG=1
    depends_on:
      - db
    # RUNE CELERY
  rune-celery:
    container_name: 'rune_celery'
    build:
      context: ./rune/rune
    command: celery --app=rune worker -l INFO
    volumes:
      - ./rune/rune:/rune/
    environment:
      - DEBUG=1
      - IMAGE_NAME=celery
    depends_on:
      - redis
  # RUNE API
  rune-api:
    container_name: 'rune_api'
    build:
      context: ./rune/rune
    command: python manage.py runserver 0.0.0.0:8334
    volumes:
      - ./rune/rune:/rune/
    ports:
      - "8334:8334"
    environment:
      - DEBUG=1
      - IMAGE_NAME=rune_api
    depends_on:
      - redis
  # VALHALLA API
  valhalla-api:
    container_name: 'valhalla_api'
    build:
      context: ./valhalla/valhalla
    command: python manage.py runserver 0.0.0.0:8335
    volumes:
      - ./valhalla/valhalla:/valhalla/
    ports:
      - "8335:8335"
    environment:
      - DEBUG=1
    stdin_open: true
    tty: true
  # ASGARD CELERY
  asgard-celery:
    container_name: 'asgard_celery'
    build:
      context: ./asgard/asgard
    command: celery --app=asgard worker -l INFO
    volumes:
      - ./asgard/asgard:/asgard/
    environment:
      - DEBUG=1
      - IMAGE_NAME=celery
    depends_on:
      - redis
  # ASGARD API
  asgard-api:
    container_name: 'asgard_api'
    build:
      context: ./asgard/asgard
    command: python manage.py runserver 0.0.0.0:8336
    volumes:
      - ./asgard/asgard:/asgard/
    ports:
      - "8336:8336"
    environment:
      - DEBUG=1
      - IMAGE_NAME=asgard_api
    depends_on:
      - redis
  # # YGGDRASIL API
  # yggdrasil-api:
  #   container_name: 'yggdrasil_api'
  #   build:
  #     context: ./yggdrasil/yggdrasil
  #   command: python manage.py runserver 0.0.0.0:8337
  #   volumes:
  #     - ./yggdrasil/yggdrasil:/yggdrasil/
  #   ports:
  #     - "8337:8337"
  #   environment:
  #     - DEBUG=1
  #     - IMAGE_NAME=yggdrasil_api
  #   depends_on:
  #     - redis
  # # RAGNAROK IMAGE
  # ragnarok:
  #   container_name: 'ragnarok'
  #   platform: linux/amd64
  #   build:
  #     context: ./ragnarok/ragnarok
  #   # command: 
  #   volumes:
  #     - ./ragnarok/ragnarok:/ragnarok/
  #   environment:
  #     - DEBUG=1
  #   stdin_open: true
  #   tty: true
  # # HIEMDALL API
  # hiemdall-api:
  #   container_name: 'hiemdall_api'
  #   build:
  #     context: ./hiemdall/hiemdall
  #   command: python manage.py runserver 0.0.0.0:8338
  #   volumes:
  #     - ./hiemdall/hiemdall:/hiemdall/
  #   ports:
  #     - "8336:8336"
  #   environment:
  #     - DEBUG=1
  #     - IMAGE_NAME=hiemdall_api
  #   depends_on:
  #     - redis
volumes:
  bolt_data:
