version: '3.8'
services:
  django:
    container_name: 'bifrost_django'
    build:
      context: ./bifrost
    command: python manage.py runserver 0.0.0.0:8332
    volumes:
      - ./bifrost:/bifrost/
    ports:
      - "8332:8332"
    environment:
      - DEBUG=1
