// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Enricher struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ApiID      uuid.UUID
	ScanID     uuid.UUID
	ScanName   string
	Power      string
	Scope      string
	Tasks      string
	Completion string
	Status     string
}
