# Generated by Django 4.2.7 on 2023-11-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(default='http', max_length=10)),
                ('port', models.IntegerField(default=80)),
                ('method', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('body', models.CharField(blank=True, max_length=1000, null=True)),
                ('target', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('root_domain', models.CharField(max_length=100)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.header')),
                ('query_param', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.query')),
            ],
        ),
    ]
