# Generated by Django 4.2.7 on 2023-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_api_protocol_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='value',
            field=models.CharField(max_length=5000),
        ),
    ]
