# Generated by Django 4.2.7 on 2023-12-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='remediation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
