# Generated by Django 4.2.7 on 2023-12-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_tag_risk_abbreviation_risk_power_risk_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='power',
            field=models.CharField(choices=[('l', 'low'), ('m', 'medium'), ('h', 'high')], max_length=1),
        ),
    ]
