# Generated by Django 4.2.7 on 2023-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_alter_risk_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='tag',
        ),
        migrations.AddField(
            model_name='risk',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='risk.tag'),
        ),
    ]
