# Generated by Django 4.2.7 on 2023-12-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_vulnerability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='power',
        ),
    ]
