# Generated by Django 4.2.7 on 2023-12-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_remove_risk_tag_remove_vulnerability_root_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='previous_workflows',
            field=models.ManyToManyField(related_name='next_workflows', to='risk.workflow'),
        ),
    ]
