# Generated by Django 4.2.7 on 2023-12-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_alter_workflow_previous_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='previous_workflows',
            field=models.ManyToManyField(blank=True, null=True, related_name='next_workflows', to='risk.workflow'),
        ),
    ]
