# Generated by Django 4.2.7 on 2023-12-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_alter_workflow_previous_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='previous_workflows',
            field=models.ManyToManyField(blank=True, related_name='next_workflows', to='risk.workflow'),
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='vulnerability',
        ),
        migrations.AddField(
            model_name='workflow',
            name='vulnerability',
            field=models.ManyToManyField(blank=True, to='risk.vulnerability'),
        ),
    ]
