# Generated by Django 4.2.7 on 2023-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_alter_workflow_previous_workflows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.FileField(upload_to=''),
        ),
    ]
