# Generated by Django 4.2.7 on 2024-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0017_vulnerability_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
