# Generated by Django 4.2.7 on 2024-01-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_alter_script_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='previous_workflows',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='script',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='vulnerability',
        ),
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
