# Generated by Django 4.2.7 on 2024-02-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_vulnerability_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.vulnerability')),
            ],
        ),
    ]
