# Generated by Django 4.2.7 on 2024-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0022_fuzzing_vulnerability_fuzzing_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuzzing',
            name='part',
            field=models.CharField(choices=[('h', 'header'), ('b', 'body'), ('q', 'query param')], default='q', max_length=10),
        ),
    ]
