# Generated by Django 4.2.7 on 2024-03-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0023_alter_fuzzing_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='steps_to_reproduce',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
