# Generated by Django 4.2.7 on 2024-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_vulnerability_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_domain', models.CharField(max_length=500)),
                ('host', models.CharField(max_length=500)),
                ('ip', models.CharField(max_length=50)),
                ('status_code', models.CharField(max_length=5)),
            ],
        ),
    ]
