# Generated by Django 4.2.7 on 2024-01-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hosts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosts',
            new_name='Host',
        ),
    ]
