# Generated by Django 4.2.7 on 2023-11-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurpExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(blank=True, max_length=500, null=True)),
                ('power', models.CharField(choices=[('l', 'low'), ('m', 'medium'), ('h', 'high')], max_length=1)),
                ('burpExport', models.FileField(upload_to='media/burpExport/')),
            ],
        ),
    ]
