# Generated by Django 4.2.7 on 2023-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burpexport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burpexport',
            name='burpExport',
            field=models.FileField(upload_to='media/burpExport/'),
        ),
    ]
