# Generated by Django 4.2.7 on 2023-12-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burpexport', '0003_alter_burpexport_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='burpexport',
            name='completion',
            field=models.IntegerField(default=0),
        ),
    ]
