# Generated by Django 4.2.7 on 2024-02-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burpexport', '0005_alter_burpexport_burpexport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burpexport',
            name='completion',
        ),
    ]
