# Generated by Django 4.2.7 on 2023-12-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enricher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('triggered', models.BooleanField(default=False)),
            ],
        ),
    ]
