# Generated by Django 4.2.7 on 2023-12-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enricher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enricher',
            name='scans',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
