# Generated by Django 4.2.7 on 2023-12-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enricher', '0002_enricher_scans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enricher',
            name='power',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')]),
        ),
    ]
