# Generated by Django 4.2.7 on 2023-12-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enricher', '0003_alter_enricher_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enricher',
            old_name='scans',
            new_name='tasks',
        ),
    ]
