# Generated by Django 4.2.7 on 2024-02-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enricher', '0004_rename_scans_enricher_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enricher',
            name='completion',
            field=models.IntegerField(default=0),
        ),
    ]
