# Generated by Django 4.2.7 on 2024-02-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enricher', '0005_enricher_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enricher',
            name='scope',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
