# Generated by Django 4.2.7 on 2024-02-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enricher', '0006_enricher_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enricher',
            name='name',
        ),
        migrations.AddField(
            model_name='enricher',
            name='scan_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
