# Generated by Django 4.2.7 on 2024-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enricher', '0007_remove_enricher_name_enricher_scan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enricher',
            name='triggered',
        ),
        migrations.AddField(
            model_name='enricher',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'running'), (3, 'success'), (4, 'failed')], default=1),
        ),
    ]
