// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Api struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Target          string
	RootDomain      string
	Domain          string
	Protocol        string
	ProtocolVersion string
	Port            string
	Method          string
	Path            string
	Body            string
}

type Header struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Value     string
	Api       uuid.UUID
}

type Query struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Value     string
	Api       uuid.UUID
}
