// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type BurpExport struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	Scope      string
	Power      string
	Burpexport string
}
